
default: &default
  adapter: postgresql
  encoding: unicode
  database: four
  username: k_a_b
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: four_test
